name: Destroy Ephemeral Environment

on:
  workflow_dispatch: # Trigger manually
    inputs:
      pr_number:
        description: 'PR Number of the ephemeral environment to destroy'
        required: true
        type: number

  pull_request: # Triggered when the PR is closed
    types:
      - closed

env:
  TF_WORKING_DIR: terraform/live/ephemeral

jobs:
  destroy-ephemeral:
    name: Destroy Ephemeral Environment
    runs-on: ubuntu-latest
    environment: ephemeral

    permissions:
      id-token: write
      contents: read
      pull-requests: write

    env:
      TF_VAR_region: ${{ secrets.AWS_REGION }}
      TF_VAR_app_id: file-uploader-eph-${{ github.event.inputs.pr_number }}
      TF_VAR_environment: ephemeral-pr-${{ github.event.inputs.pr_number }}
      TF_VAR_api_file_upload_domain_name: eph-pr${{ github.event.inputs.pr_number }}-api-file-upload.epic-trip-planner.com
      TF_VAR_backend_certificate_arn: ${{ secrets.BACKEND_CERTIFICATE_ARN }}
      TF_VAR_uploads_bucket_name: file-upload-bucket-eph-pr${{ github.event.inputs.pr_number }}
      TF_VAR_enable_transfer_acceleration: false
      TF_VAR_secret_store_name: ${{ secrets.SECRET_STORE_NAME }}
      TF_VAR_route53_zone_name: epic-trip-planner.com

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::387836084035:role/gitHubFileUploader
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init with backend
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform init -input=false

      - name: Terraform Destroy
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform destroy -auto-approve

      - name: Comment destroy success
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = "${{ github.event.inputs.pr_number }}";
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: `### üóëÔ∏è Ephemeral Environment Destroyed\nAll resources for ephemeral-pr-${prNumber} have been destroyed successfully.`
            });
